title: Wenjie Jiang's Homepage
page-top-title: Wenjie Jiang
top-section-bg-text: Computer Science
home-subtitle: Wenjie Jiang&ensp;|&ensp;姜文杰
copyright-text: '&copy; Wenjie Jiang 2023-2025. All Rights Reserved.'
